name: DSP Library Checks
on:
  # run for all pull requests
  # Run for all commits on feature branches
  push:
    paths:
    - 'dsp/**'
    - 'lib/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'dsp/**'
    - 'lib/**'
    - '.github/workflows/**'
jobs:

###############################################################################
  # builds the automated tests with clang; runs tests and exports results
  dsp-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        cd dsp/tests
        make release
    
    - name: Run Tests
      run: |
        cd dsp/tests/build/bin
        ./TapeLooperDSP_gtest --gtest_output=xml:gtestresults.xml
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: dsp/tests/build/bin/**/*.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}