name: Formatting
on:
  # run for all pull requests
  # Run for all commits on feature branches
  push:
    paths:
    - 'firmware/**'
    - 'dsp/**'
    - 'plugin/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'firmware/**'
    - 'dsp/**'
    - 'plugin/**'
    - '.github/workflows/**'
jobs:
  ###############################################################################
  # checks the formatting with clang-format
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'firmware/src' 
          - 'firmware/tests' 
          - 'dsp/src'
          - 'dsp/tests'
          - 'plugin/src'
          - 'plugin/tests'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v3.4.0
      with:
        clang-format-version: '11'
        check-path: ${{ matrix.path }}